FROM fedora:latest
RUN dnf install -y update
RUN dnf install -y tuxpaint vim httpd
CMD httpd -D foreground
EXPOSE 80
COPY data/myinfo.html /var/www/html/myinfo.html
RUN dnf remove -y tuxpaint 
RUN dnf remove -y vim 
