FROM fedora:latest AS baseline
RUN dnf install -y httpd
EXPOSE 80
ENTRYPOINT httpd -D FOREGROUND

FROM baseline AS website1
COPY website1.html /var/www/html/
LABEL website=1

FROM base AS website2
COPY website2.html /var/www/html/
LABEL website=2
